### PR TITLE
6 sendurl not working on deployed docker

### LINKED ISSUE #6: /sendURL not working on deployed docker
Image

Cannot see console logs errors

### PR DESCRIPTION
**Pull request by elkofy**

### CODE REVIEW

File: infrastructure/discord/commands/sendUrl.ts [hunk 1]
```diff
@@ -125,6 +135,6 @@ const requestedDownload = test.requested_downloads[0] as Record<string, unknown>
   }
     catch (error) {
         console.error(error);
-        await interaction.editReply("An error occurred.");
+        await interaction.followUp("tets An error occurred while sending the media chat.");
```
Comment (R0bas) [inline infrastructure/discord/commands/sendUrl.ts]:
```suggestion
        await interaction.followUp("An error occurred while sending the media chat.");
```

File: docker-compose.yml [hunk 2]
```diff
@@ -4,6 +4,8 @@ services:
       context: .
       dockerfile: infrastructure/express/Dockerfile
       target: production
+    ports:
+      - 3000:3000
```
Comment (R0bas) [inline docker-compose.yml]:
```suggestion
```

**Review by R0bas — CHANGES_REQUESTED** [review]
PLUS VITE PLUS VITE
